### ISSUE TITLE
Conflict with Draconic Evolution

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/DimensionStages#2]
Modpack: Modern Skyblock 3 v3.4.2
Dimension Stages Version: 1.12.2-2.0.20
Draconic Evolution Version: 1.12.2-2.3.13.306

When dimension stages is enabled, on a multiplayer server in survival mode, key items cannot be placed into fusion injectors. As in this pack, said items are behind stages, I believe some option in dimension stages is broken. I cannot find the config for this mod, despite the mod commands implying there should be one.

As this mod is not particularly relevant to anyone playing on the server I'm on, it will be left removed.

**Comment by DemonfangArun** [comment]
> 
> 
> I am not sure how the fusion injectors work, so if you could give me more info about that, it may help work out this issue. As it stands now, this mod only interacts with items in one way, which is when the have been thrown on the ground, and then they move into a portal. If you don't have the permission to go to that dimension you wont be allowed in, and neither will items you have thrown.

As an update to this, I have found that installing the previous version of this mod, with no other changes fixes the issue. I have a feeling more was changed than merely the version info.

**Comment by DemonfangArun** [comment]
As a final addendum

The only further updates to gamestages as of the time of this message are alpha, and I don't use alpha or beta versions of a mod unless nothing else is available. If something breaks because mod incompatibility, I will review it at that time and take action. For right now, my agenda was to get everything working and it is.

Other notes:
-removing this mod somehow renders gamestages as a whole broken (it still runs, but there is no enforcement of anything, indications of itemstages are also gone)
  >when this happens, project e emc autocalculation starts working. I'm not sure how they are related, but I wanted to make a note of it in case it's of use (this is probably related more to itemstages).

-and finally, I will say that I'm not a developer and will not pretend to know what's going on. I will just state what I have been able to comprehend of a complex set of mods that I have never worked with before. I apologize if I have offended you in any way.

And now, a question. Dimension Stages is clearly configurable, but I have not been able to locate its config. Does it have one, and where can I find it?

**Comment by darkhax** [comment]
DimensionStages uses CraftTweaker for configuration, so the modpack author creates simple scripts to set the various options of the mod. This means that the file could be anywhere in the /scripts folder. Additionally, removing this mod will cause CraftTweaker to stop loading any script that uses this mod, which means if he has all the gamestage scripts in one file, that file wont load correctly. 

Ultimately you should be reporting this to the modpack author so they can fix it in an appropriate way.

**Comment by DemonfangArun** [comment]
Thank you for the insight. I will do such.
